/**
 * Terrain wind influence layer.
 *
 * Consumes a 512×512 RG influence field generated by another agent:
 *   R = speed multiplier (0.15 deep lee → 1.35 gap acceleration)
 *   G = direction bias (±45° encoded as 0..1 → -π/4..+π/4)
 *
 * Bilinear-interpolated and blended by distance from shore so the effect
 * fades smoothly in open water. Provides a neutral/identity default so the
 * wind system works without the terrain generator being ready.
 */

import type { Radians } from '@/types';
import { clamp, lerp } from '@core/math';

const MAX_DIRECTION_BIAS = (45 * Math.PI) / 180; // ±45° maximum terrain deflection

/**
 * Interface for the terrain influence field. Another agent generates this;
 * we consume it through this minimal contract.
 */
export interface TerrainInfluenceField {
  /** The raw RG data — R in even indices, G in odd. 512×512 pixels, 2 floats each. */
  readonly data: Float32Array;
  /** World-space origin (south-west corner) of the influence field. */
  readonly originX: number;
  readonly originZ: number;
  /** World-space extent of the field. */
  readonly extentX: number;
  readonly extentZ: number;
  /** Pixel resolution per axis. */
  readonly resolution: number;
}

/**
 * Neutral identity field: speed multiplier = 1, direction bias = 0.
 * Used when no terrain data is available.
 */
export function createNeutralTerrainField(): TerrainInfluenceField {
  // A 1×1 field filled with identity values (speed=1, bias=0.5 meaning 0°).
  const data = new Float32Array(2);
  data[0] = 1.0; // speed multiplier
  data[1] = 0.5; // direction bias at neutral (maps to 0 radians)
  return {
    data,
    originX: -1e6,
    originZ: -1e6,
    extentX: 2e6,
    extentZ: 2e6,
    resolution: 1,
  };
}

export interface TerrainSample {
  speedMultiplier: number;
  directionBias: Radians;
}

/**
 * Sample the terrain influence at a world position with bilinear interpolation.
 * Writes into the provided `out` to avoid allocation.
 */
export function sampleTerrainInfluence(
  field: TerrainInfluenceField,
  x: number,
  z: number,
  out: TerrainSample,
): TerrainSample {
  const res = field.resolution;

  // Normalized position within the field [0, 1].
  const u = (x - field.originX) / field.extentX;
  const v = (z - field.originZ) / field.extentZ;

  // If outside the field, return identity.
  if (u < 0 || u >= 1 || v < 0 || v >= 1) {
    out.speedMultiplier = 1.0;
    out.directionBias = 0;
    return out;
  }

  // Pixel coordinates (continuous).
  const px = u * (res - 1);
  const py = v * (res - 1);

  // Integer corners for bilinear.
  const ix = Math.floor(px);
  const iy = Math.floor(py);
  const fx = px - ix;
  const fy = py - iy;

  // Clamp to valid range.
  const ix1 = Math.min(ix + 1, res - 1);
  const iy1 = Math.min(iy + 1, res - 1);

  // Read the four corners (stride = 2 floats per pixel, row-major).
  const stride = res * 2;
  const i00 = iy * stride + ix * 2;
  const i10 = iy * stride + ix1 * 2;
  const i01 = iy1 * stride + ix * 2;
  const i11 = iy1 * stride + ix1 * 2;

  const r00 = field.data[i00] ?? 1;
  const g00 = field.data[i00 + 1] ?? 0.5;
  const r10 = field.data[i10] ?? 1;
  const g10 = field.data[i10 + 1] ?? 0.5;
  const r01 = field.data[i01] ?? 1;
  const g01 = field.data[i01 + 1] ?? 0.5;
  const r11 = field.data[i11] ?? 1;
  const g11 = field.data[i11 + 1] ?? 0.5;

  // Bilinear interpolation.
  const r = lerp(lerp(r00, r10, fx), lerp(r01, r11, fx), fy);
  const g = lerp(lerp(g00, g10, fx), lerp(g01, g11, fx), fy);

  out.speedMultiplier = clamp(r, 0.15, 1.35);
  // G channel encodes direction bias: 0 → -45°, 0.5 → 0°, 1 → +45°.
  out.directionBias = (g - 0.5) * 2 * MAX_DIRECTION_BIAS;

  return out;
}
